### ISSUE TITLE
AttributeError: 'str' object has no attribute 'detach'

### ISSUE THREAD

**Issue by Gooddz1** [huggingface/quanto#175]
Why does exporting the quantized model to the onnx model result in the following error 
 
AttributeError: 'str' object has no attribute 'detach'

**Comment by dacorvo** [comment]
Exporting the model to ONNX is not a feature provided by quanto itself.
Please:
- explain what you are trying to achieve,
- provide the exact command you ran,
- give the error log, including the whole backtrace.

**Comment by Gooddz1** [comment]
Run the following code，export the model to ONNX
```
import torch
import torch.nn.functional as F
from quanto import Calibration, QTensor, freeze, qint2, qint4, qint8, quantize
from torch import nn

# 定义一个简单的 CNN 模型
class SimpleCNN(nn.Module):
    def __init__(self):
        super(SimpleCNN, self).__init__()
        self.conv1 = nn.Conv2d(1, 32, 3, 1)
        self.conv2 = nn.Conv2d(32, 64, 3, 1)
        self.dropout1 = nn.Dropout2d(0.25)
        self.dropout2 = nn.Dropout2d(0.5)
        self.fc1 = nn.Linear(9216, 128)
        self.fc2 = nn.Linear(128, 10)

    def forward(self, x):
        x = self.conv1(x)
        x = F.relu(x)
        x = self.conv2(x)
        x = F.relu(x)
        x = F.max_pool2d(x, 2)
        x = self.dropout1(x)
        x = torch.flatten(x, 1)
        x = self.fc1(x)
        x = F.relu(x)
        x = self.dropout2(x)
        x = self.fc2(x)
        output = F.log_softmax(x, dim=1)
        return output
if __name__ == "__main__":
    model = SimpleCNN()
    quantize(model, weights=qint8, activations=qint8)
    freeze(model)
    # 创建模拟输入数据
    x = torch.randn(1, 3, 28, 28)

    # 设置模型的输出文件的名称
    onnx_file_name = "resnet18.onnx"

    # 导出模型
    torch.onnx.export(model,               # 要导出的模型
                    x,                   # 模型的输入数据
                    onnx_file_name,      # 输出文件的名称 
                    export_params=True,  # 是否导出模型参数  
                    opset_version=12,    # ONNX版本
                    do_constant_folding=True,  # 是否执行常量折叠优化
                    )
```
The following error has occurred
```
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda-10.2'
Traceback (most recent call last):
  File "quanto_yolov8.py", line 42, in <module>
    torch.onnx.export(model,               # 要导出的模型
  File "/home/sta/anaconda3/envs/quanto/lib/python3.8/site-packages/torch/onnx/utils.py", line 516, in export
    _export(
  File "/home/sta/anaconda3/envs/quanto/lib/python3.8/site-packages/torch/onnx/utils.py", line 1613, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "/home/sta/anaconda3/envs/quanto/lib/python3.8/site-packages/torch/onnx/utils.py", line 1135, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
  File "/home/sta/anaconda3/envs/quanto/lib/python3.8/site-packages/torch/onnx/utils.py", line 1011, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "/home/sta/anaconda3/envs/quanto/lib/python3.8/site-packages/torch/onnx/utils.py", line 907, in _trace_and_get_graph_from_model
    orig_state_dict_keys = torch.jit._unique_state_dict(model).keys()
  File "/home/sta/anaconda3/envs/quanto/lib/python3.8/site-packages/torch/jit/_trace.py", line 81, in _unique_state_dict
    filtered_dict[k] = v.detach()
AttributeError: 'str' object has no attribute 'detach'
```

**Comment by dacorvo** [comment]
This is probably because the quantized models state_dict does not contain only tensors, but also string metadata, which seem to make the torch.onnx code choke. If you want torch.onnx to support exporting quanto models, please submit an issue there.

**Comment by Gooddz1** [comment]
I want torch.onnx to support exporting quanto models.But Quanto doesn't support converting to ONNX model, right?

> This is probably because the quantized models state_dict does not contain only tensors, but also string metadata, which seem to make the torch.onnx code choke. If you want torch.onnx to support exporting quanto models, please submit an issue there.
I want torch.onnx to support exporting quanto models

**Comment by dacorvo** [comment]
No, this is out-of-scope.
